clear; clc;

Path_MainFolder = ['D:\Google\我的雲端硬碟\學術｜研究與論文\論文著作\', ...
    'MLE Pricing Kernel'];

Path_Data      = fullfile(Path_MainFolder, 'Code', '00  Output');
Path_RND       = fullfile(Path_MainFolder, 'Code', '01  Output');
Path_Code_18   = fullfile(Path_MainFolder, 'Code', ...
    '18  Simulation - Model Comparison');
Path_Output_18 = fullfile(Path_MainFolder, 'Code', ...
    '18  Output - 50 pilot & alpha');

addpath(Path_Code_18);

if ~exist(Path_Output_18, 'dir')
    mkdir(Path_Output_18);
end


%% Simulation settings

Target_TTM = 30;
b = 6;

Num_Simulations = 200;
Num_Bins_List = [10, 20];
Requested_Num_Workers = 6;
% Save a checkpoint after each worker-sized batch.
Batch_Size_Multiplier = 1;
Base_Seed = 42;
Reuse_Observed_Fits = true;

% Case 1: both candidate models are undistorted. The only difference is
% whether the SDF monotonicity restriction is imposed.
Shape_Alpha = 1.00;
Shape_Beta = 1.00;

% Case 2: estimate alpha while fixing beta at one. The same adaptive rule
% is applied to the observed sample and every simulated sample.
Distortion_Fixed_Alpha = 1.00;
Distortion_Fixed_Beta = 1.00;

Distortion_Search_Settings = struct( ...
    'SearchStrategy', "directional_bracket", ...
    'Parameter', "alpha", ...
    'NullValue', 1.00, ...
    'CoarseGrid', (0.9:0.1:1.1)', ...
    'CoarseStep', 0.10, ...
    'FineStep', 0.05, ...
    'LowerBoundExclusive', 0.00, ...
    'UpperBoundInclusive', 2.00, ...
    'LikelihoodTolerance', 1e-6, ...
    'NonImprovingToStop', 2, ...
    'MaxExpansionSteps', 50);

% First stage: Case 1 and Case 2 pairwise tests plus the common-null PIT
% uniformity test. Alternative-model PIT uniformity runs remain separate.
Run_Joint_Null_Tests = true;


%% Load realized returns

FileName = ['Realized_Return_TTM_', num2str(Target_TTM), '.csv'];
Realized_Return = readtable(fullfile(Path_Data, FileName));


%% Load risk-free gross factors

FileName = 'Risk_Free_GrossFactor_ByTargetTTM.csv';
Risk_Free_Rate_All = readtable(fullfile(Path_Data, FileName));


%% Load Q-measure PDF tables

Smooth_AllR = [];
Smooth_AllR_RND = [];

years_to_merge = 1996:2025;

for year = years_to_merge
    input_filename = fullfile(Path_RND, ...
        sprintf('TTM_%d_RND_Tables_%d.mat', Target_TTM, year));

    if exist(input_filename, 'file')
        Loaded = load(input_filename);
        Smooth_AllR = [Smooth_AllR, ...
            Loaded.Table_Smooth_AllR]; %#ok<AGROW>
        Smooth_AllR_RND = [Smooth_AllR_RND, ...
            Loaded.Table_Smooth_AllR_RND]; %#ok<AGROW>
    else
        warning('File %s does not exist.', input_filename);
    end
end

clear Loaded FileName input_filename year


%% Align RND, realized returns, and risk-free rates

rnd_var_names = string(Smooth_AllR_RND.Properties.VariableNames);
rnd_dates = str2double(regexp( ...
    rnd_var_names, '\d+', 'match', 'once'));

realized_dates = double(Realized_Return.date);

rf_date_col = ['date_', num2str(Target_TTM)];
rf_rate_col = ['rf_gross_TTM', num2str(Target_TTM)];

rf_dates_all  = double(Risk_Free_Rate_All.(rf_date_col));
rf_values_all = double(Risk_Free_Rate_All.(rf_rate_col));

idx_rf_valid = isfinite(rf_dates_all) & isfinite(rf_values_all);
rf_dates_all  = rf_dates_all(idx_rf_valid);
rf_values_all = rf_values_all(idx_rf_valid);

idx_master = ...
    ismember(realized_dates, rnd_dates) & ...
    ismember(realized_dates, rf_dates_all);

common_dates = sort(realized_dates(idx_master));

if isempty(common_dates)
    error('No common dates across the three input datasets.');
end

[tf_rnd, idx_rnd] = ismember(common_dates, rnd_dates);
[tf_ret, idx_ret] = ismember(common_dates, realized_dates);
[tf_rf, idx_rf] = ismember(common_dates, rf_dates_all);

if ~all(tf_rnd) || ~all(tf_ret) || ~all(tf_rf)
    error('Date alignment failed.');
end

Smooth_AllR = Smooth_AllR(:, idx_rnd);
Smooth_AllR_RND = Smooth_AllR_RND(:, idx_rnd);
Realized_Return = Realized_Return(idx_ret, :);
Risk_Free_Rate = rf_values_all(idx_rf);

R_observed = Realized_Return.realized_ret(:);
Risk_Free_Rate = Risk_Free_Rate(:);

fprintf('\nAligned sample: %d months, %08.0f to %08.0f.\n', ...
    numel(common_dates), common_dates(1), common_dates(end));

clear idx_master idx_rf_valid idx_rnd idx_ret idx_rf
clear tf_rnd tf_ret tf_rf rnd_dates realized_dates
clear rf_dates_all rf_values_all rf_date_col rf_rate_col
clear Risk_Free_Rate_All rnd_var_names


%% Global return range and precomputed monthly inputs

Global_Min_R = Inf;
Global_Max_R = -Inf;
months = Smooth_AllR.Properties.VariableNames;

for t = 1:numel(months)
    R_axis_t = Smooth_AllR.(months{t});
    Global_Min_R = min(Global_Min_R, min(R_axis_t));
    Global_Max_R = max(Global_Max_R, max(R_axis_t));
end

Global_Min_R = Global_Min_R * 0.9;
Global_Max_R = Global_Max_R * 1.1;

n_degree = 5;
k_order = n_degree + 1;
num_basis_function = b + 1;
num_breaks = num_basis_function - k_order + 2;
breaks = linspace(Global_Min_R, Global_Max_R, num_breaks);
knots = augknt(breaks, k_order);

T = numel(R_observed);
Basis_Precomputed = cell(T, 1);

Monthly_Precomputed = struct();
Monthly_Precomputed.R_Axis = cell(T, 1);
Monthly_Precomputed.fQ = cell(T, 1);
Monthly_Precomputed.Log_fQ = cell(T, 1);
Monthly_Precomputed.Basis = cell(T, 1);

for t = 1:T
    R_axis_t = Smooth_AllR.(months{t});
    fQ_t = Smooth_AllR_RND.(months{t});

    R_axis_t = R_axis_t(:);
    fQ_t = fQ_t(:);

    if any(fQ_t < 0) || any(~isfinite(fQ_t))
        error('Invalid RND values at t=%d (%s).', t, months{t});
    end

    Basis_Precomputed{t} = spcol(knots, k_order, R_axis_t);
    Monthly_Precomputed.R_Axis{t} = R_axis_t;
    Monthly_Precomputed.fQ{t} = fQ_t;
    Monthly_Precomputed.Log_fQ{t} = log(fQ_t);
    Monthly_Precomputed.Basis{t} = Basis_Precomputed{t};
end


%% Load compatible observed fits, or estimate them when needed

Observed_Fits_File = fullfile( ...
    Path_Output_18, 'Observed_Model_Fits.mat');

Observed_Fit_Settings = struct( ...
    'Version', "joint_alpha_directional_v2", ...
    'Target_TTM', Target_TTM, ...
    'b', b, ...
    'Sample_Dates', common_dates(:), ...
    'Observed_Returns', R_observed, ...
    'Risk_Free_Rate', Risk_Free_Rate, ...
    'Global_Min_R', Global_Min_R, ...
    'Global_Max_R', Global_Max_R, ...
    'Shape_Alpha', Shape_Alpha, ...
    'Shape_Beta', Shape_Beta, ...
    'Distortion_Fixed_Alpha', Distortion_Fixed_Alpha, ...
    'Distortion_Fixed_Beta', Distortion_Fixed_Beta, ...
    'Distortion_Search_Settings', Distortion_Search_Settings);

Loaded_Observed_Fits = false;

if Reuse_Observed_Fits && exist(Observed_Fits_File, 'file')
    Saved_Observed = load(Observed_Fits_File);

    Loaded_Observed_Fits = ...
        isfield(Saved_Observed, 'Observed_Fits') && ...
        isfield(Saved_Observed, 'Observed_Fit_Settings') && ...
        isequaln( ...
            Saved_Observed.Observed_Fit_Settings, ...
            Observed_Fit_Settings) && ...
        all(isfield(Saved_Observed.Observed_Fits, { ...
            'Null', 'ShapeAlternative', ...
            'DistortionAlternative'}));
end

if Loaded_Observed_Fits
    fprintf('\nLoading compatible observed-data model fits:\n%s\n', ...
        Observed_Fits_File);

    Observed_Fits = Saved_Observed.Observed_Fits;

    theta_0 = Observed_Fits.Null.theta;
    LL_0 = Observed_Fits.Null.LL;
    exit_0 = Observed_Fits.Null.exitflag;

    theta_U = Observed_Fits.ShapeAlternative.theta;
    LL_U = Observed_Fits.ShapeAlternative.LL;
    exit_U = Observed_Fits.ShapeAlternative.exitflag;

    theta_D = Observed_Fits.DistortionAlternative.theta;
    LL_D = Observed_Fits.DistortionAlternative.LL;
    exit_D = Observed_Fits.DistortionAlternative.exitflag;
    output_D = Observed_Fits.DistortionAlternative.search_output;
    alpha_D_hat = output_D.SelectedAlpha;
    beta_D_hat = output_D.SelectedBeta;

    fprintf('Observed MLEs are reused.\n');
    fprintf('Loaded observed alpha estimate: %.3f\n', alpha_D_hat);
else
    fprintf('\nEstimating observed-data models...\n');
    Observed_Timer = tic;

    fprintf('[Observed 1/3] Estimating common null model...\n');
    [theta_0, LL_0, ~, exit_0] = MLE_BSpline_estimation( ...
        Smooth_AllR, Smooth_AllR_RND, ...
        Realized_Return, Risk_Free_Rate, ...
        b, Shape_Alpha, Shape_Beta, ...
        Global_Min_R, Global_Max_R, ...
        true, Basis_Precomputed, [], Monthly_Precomputed);
    fprintf('[Observed 1/3] Common null completed. LL = %.6f\n', ...
        LL_0);

    fprintf('[Observed 2/3] Estimating unconstrained SDF model...\n');
    [theta_U, LL_U, ~, exit_U] = MLE_BSpline_estimation( ...
        Smooth_AllR, Smooth_AllR_RND, ...
        Realized_Return, Risk_Free_Rate, ...
        b, Shape_Alpha, Shape_Beta, ...
        Global_Min_R, Global_Max_R, ...
        false, Basis_Precomputed, [], Monthly_Precomputed);
    fprintf('[Observed 2/3] Unconstrained model completed. LL = %.6f\n', ...
        LL_U);

    fprintf(['[Observed 3/3] Estimating alpha-distortion model ', ...
        'with adaptive search...\n']);

    % Alpha=1 is exactly the constrained undistorted null already fitted
    % above. Reuse it as one search candidate instead of running the same
    % fmincon problem twice.
    Observed_Distortion_Search = Distortion_Search_Settings;
    Observed_Distortion_Search.CachedCandidate = struct( ...
        'Parameter', "alpha", ...
        'Value', Shape_Alpha, ...
        'Theta', theta_0, ...
        'LogLikelihood', LL_0, ...
        'BIC', NaN, ...
        'ExitFlag', exit_0, ...
        'OptimizerOutput', struct());

    [theta_D, LL_D, ~, exit_D, output_D] = ...
        MLE_BSpline_estimation( ...
            Smooth_AllR, Smooth_AllR_RND, ...
            Realized_Return, Risk_Free_Rate, ...
            b, Distortion_Fixed_Alpha, ...
            Distortion_Fixed_Beta, ...
            Global_Min_R, Global_Max_R, ...
            true, Basis_Precomputed, ...
            Observed_Distortion_Search, ...
            Monthly_Precomputed);

    alpha_D_hat = output_D.SelectedAlpha;
    beta_D_hat = output_D.SelectedBeta;

    fprintf([ ...
        '[Observed 3/3] Alpha-distortion model completed. ', ...
        'Selected alpha = %.3f, beta = %.3f, LL = %.6f\n'], ...
        alpha_D_hat, beta_D_hat, LL_D);
    fprintf('All observed-data models completed in %.2f minutes.\n', ...
        toc(Observed_Timer) / 60);

    Observed_Fits = struct();
    Observed_Fits.Null = struct( ...
        'theta', theta_0, 'LL', LL_0, ...
        'alpha', Shape_Alpha, 'beta', Shape_Beta, ...
        'exitflag', exit_0);
    Observed_Fits.ShapeAlternative = struct( ...
        'theta', theta_U, 'LL', LL_U, ...
        'alpha', Shape_Alpha, 'beta', Shape_Beta, ...
        'exitflag', exit_U);
    Observed_Fits.DistortionAlternative = struct( ...
        'theta', theta_D, 'LL', LL_D, ...
        'alpha', alpha_D_hat, 'beta', beta_D_hat, ...
        'exitflag', exit_D, ...
        'search_output', output_D);

    save(Observed_Fits_File, ...
        'Observed_Fits', 'Observed_Fit_Settings', '-v7.3');
end


%% Construct the common month-specific null DGP CDFs

[R_Axis_0, F_0] = build_physical_cdf_bspline( ...
    theta_0, Risk_Free_Rate, Basis_Precomputed, ...
    Smooth_AllR, Smooth_AllR_RND, months, ...
    Shape_Alpha, Shape_Beta);


%% Observed PIT statistics

[~, ~, ~, ~, pit_0] = log_likelihood_bspline( ...
    theta_0, R_observed, Risk_Free_Rate, ...
    Basis_Precomputed, Smooth_AllR, Smooth_AllR_RND, ...
    months, Shape_Alpha, Shape_Beta, Monthly_Precomputed);

[~, ~, ~, ~, pit_U] = log_likelihood_bspline( ...
    theta_U, R_observed, Risk_Free_Rate, ...
    Basis_Precomputed, Smooth_AllR, Smooth_AllR_RND, ...
    months, Shape_Alpha, Shape_Beta, Monthly_Precomputed);

[~, ~, ~, ~, pit_D] = log_likelihood_bspline( ...
    theta_D, R_observed, Risk_Free_Rate, ...
    Basis_Precomputed, Smooth_AllR, Smooth_AllR_RND, ...
    months, alpha_D_hat, beta_D_hat, Monthly_Precomputed);

Observed_PIT = struct();
num_bin_settings = numel(Num_Bins_List);

Observed_Delta_Shape = nan(1, num_bin_settings);
Observed_Delta_Distortion = nan(1, num_bin_settings);
Observed_Sup_Null = nan(1, num_bin_settings);
Observed_Sup_Shape = nan(1, num_bin_settings);
Observed_Sup_Distortion = nan(1, num_bin_settings);

for bin_idx = 1:num_bin_settings
    num_bins_now = Num_Bins_List(bin_idx);
    field_name = sprintf('Bins%d', num_bins_now);

    Observed_PIT.(field_name).Null = ...
        compute_pit_statistics(pit_0, num_bins_now);
    Observed_PIT.(field_name).ShapeAlternative = ...
        compute_pit_statistics(pit_U, num_bins_now);
    Observed_PIT.(field_name).DistortionAlternative = ...
        compute_pit_statistics(pit_D, num_bins_now);

    Observed_Delta_Shape(bin_idx) = max(abs( ...
        Observed_PIT.(field_name).Null.BinProbability - ...
        Observed_PIT.(field_name).ShapeAlternative.BinProbability));

    Observed_Delta_Distortion(bin_idx) = max(abs( ...
        Observed_PIT.(field_name).Null.BinProbability - ...
        Observed_PIT.(field_name).DistortionAlternative.BinProbability));

    Observed_Sup_Null(bin_idx) = ...
        Observed_PIT.(field_name).Null.SupUniform;
    Observed_Sup_Shape(bin_idx) = ...
        Observed_PIT.(field_name).ShapeAlternative.SupUniform;
    Observed_Sup_Distortion(bin_idx) = ...
        Observed_PIT.(field_name).DistortionAlternative.SupUniform;
end

save(fullfile(Path_Output_18, 'Observed_PIT_Statistics.mat'), ...
    'Observed_PIT', 'Num_Bins_List', ...
    'Observed_Delta_Shape', 'Observed_Delta_Distortion', ...
    'Observed_Sup_Null', 'Observed_Sup_Shape', ...
    'Observed_Sup_Distortion');


%% Data and models shared by the joint null simulation

Data = struct();
Data.Smooth_AllR = Smooth_AllR;
Data.Smooth_AllR_RND = Smooth_AllR_RND;
Data.Realized_Return_Template = Realized_Return;
Data.Risk_Free_Rate = Risk_Free_Rate;
Data.Basis_Precomputed = Basis_Precomputed;
Data.Monthly_Precomputed = Monthly_Precomputed;
Data.months = months;
Data.b = b;
Data.Global_Min_R = Global_Min_R;
Data.Global_Max_R = Global_Max_R;

Model_Null = struct( ...
    'Name', 'Common constrained-undistorted null', ...
    'Alpha', Shape_Alpha, ...
    'Beta', Shape_Beta, ...
    'ImposeMonotonicity', true, ...
    'SearchSettings', []);

Model_Shape = struct( ...
    'Name', 'Unconstrained SDF', ...
    'Alpha', Shape_Alpha, ...
    'Beta', Shape_Beta, ...
    'ImposeMonotonicity', false, ...
    'SearchSettings', []);

Model_Distortion = struct( ...
    'Name', 'Alpha estimated', ...
    'Alpha', Distortion_Fixed_Alpha, ...
    'Beta', Distortion_Fixed_Beta, ...
    'ImposeMonotonicity', true, ...
    'SearchSettings', Distortion_Search_Settings);

Joint_Experiment = struct( ...
    'Name', 'Joint null tests: shape and alpha distortion', ...
    'Version', "joint_alpha_directional_v2", ...
    'DGP_R_Axis', {R_Axis_0}, ...
    'DGP_CDF', {F_0}, ...
    'ModelNull', Model_Null, ...
    'ModelShape', Model_Shape, ...
    'ModelDistortion', Model_Distortion, ...
    'ObservedLRShape', 2 * (LL_U - LL_0), ...
    'ObservedLRDistortion', 2 * (LL_D - LL_0), ...
    'ObservedDeltaShape', Observed_Delta_Shape, ...
    'ObservedDeltaDistortion', Observed_Delta_Distortion, ...
    'ObservedSupNull', Observed_Sup_Null);


%% Run the selected joint null simulation

if Run_Joint_Null_Tests
    Pool = gcp('nocreate');

    if isempty(Pool)
        Local_Cluster = parcluster('local');
        Actual_Num_Workers = min( ...
            Requested_Num_Workers, Local_Cluster.NumWorkers);
        Pool = parpool(Local_Cluster, Actual_Num_Workers);
    else
        Actual_Num_Workers = Pool.NumWorkers;
    end

    Batch_Size = max( ...
        Actual_Num_Workers, ...
        Batch_Size_Multiplier * Actual_Num_Workers);

    fprintf('\nParallel workers: %d. Batch size: %d.\n', ...
        Actual_Num_Workers, Batch_Size);

    Joint_Results = run_simulation_experiment( ...
        Joint_Experiment, Data, ...
        Num_Simulations, Num_Bins_List, ...
        Base_Seed, Batch_Size, Path_Output_18);
end


fprintf('\nAll selected simulation experiments are complete.\n');
