clear; clc; close all;

%% Paths

Path_MainFolder = ['D:\Google\我的雲端硬碟\學術｜研究與論文\論文著作\', ...
    'MLE Pricing Kernel'];

Path_Code_18 = fullfile(Path_MainFolder, 'Code', ...
    '18  Simulation - Model Comparison');
Path_Output_18 = fullfile(Path_MainFolder, 'Code', '18  Output');

Folder_Shape = fullfile(Path_Output_18, ...
    '01_Shape_Null_ConstraintDGP');
Folder_Distortion = fullfile(Path_Output_18, ...
    '03_Distortion_Null_UndistortedDGP');

assert(isfolder(Path_Code_18), ...
    'Code folder not found: %s', Path_Code_18);
assert(isfolder(Path_Output_18), ...
    'Output folder not found: %s', Path_Output_18);
assert(isfolder(Folder_Shape), ...
    'Shape-result folder not found: %s', Folder_Shape);
assert(isfolder(Folder_Distortion), ...
    'Distortion-result folder not found: %s', Folder_Distortion);


%% Load the 50-replication pilot results

Shape_10 = readtable(fullfile(Folder_Shape, ...
    'Simulation_Scalars_Bins10.csv'));
Shape_20 = readtable(fullfile(Folder_Shape, ...
    'Simulation_Scalars_Bins20.csv'));
Shape_Summary = readtable(fullfile(Folder_Shape, ...
    'Simulation_Summary_AllBins.csv'));

Distortion_10 = readtable(fullfile(Folder_Distortion, ...
    'Simulation_Scalars_Bins10.csv'));
Distortion_20 = readtable(fullfile(Folder_Distortion, ...
    'Simulation_Scalars_Bins20.csv'));
Distortion_Summary = readtable(fullfile(Folder_Distortion, ...
    'Simulation_Summary_AllBins.csv'));

Shape_Summary_10 = get_summary_row(Shape_Summary, 10);
Shape_Summary_20 = get_summary_row(Shape_Summary, 20);
Distortion_Summary_10 = get_summary_row( ...
    Distortion_Summary, 10);
Distortion_Summary_20 = get_summary_row( ...
    Distortion_Summary, 20);

Num_Shape = height(Shape_10);
Num_Distortion = height(Distortion_10);

assert(Num_Shape == height(Shape_20), ...
    'Shape CSV files contain different numbers of replications.');
assert(Num_Distortion == height(Distortion_20), ...
    'Distortion CSV files contain different numbers of replications.');
assert(all(isfinite(Shape_10.TestStatistic)), ...
    'Shape LR statistics contain non-finite values.');
assert(all(isfinite(Distortion_10.TestStatistic)), ...
    'Distortion LR statistics contain non-finite values.');
assert(all(isfinite(Distortion_10.Beta_B)), ...
    'Estimated beta values contain non-finite values.');

fprintf('Loaded Case 1: %d successful replications.\n', ...
    Num_Shape);
fprintf('Loaded Case 2: %d successful replications.\n', ...
    Num_Distortion);


%% Common plot settings

set(groot, 'defaultAxesFontName', 'Times New Roman');
set(groot, 'defaultAxesFontSize', 14);
set(groot, 'defaultAxesToolbarVisible', 'off');
set(groot, 'defaultTextFontName', 'Times New Roman');
set(groot, 'defaultLegendFontName', 'Times New Roman');
set(groot, 'defaultLegendInterpreter', 'latex');
set(groot, 'defaultTextInterpreter', 'latex');

Resolution = 300;

Color_All = [0.72, 0.78, 0.84];
Color_Tail = [0.78, 0.39, 0.30];
Color_Observed = [0.72, 0.16, 0.14];
Color_Critical = [0.16, 0.18, 0.20];
Color_Beta = [0.35, 0.55, 0.70];


%% Figure 1: Case 1 simulated null distributions

Figure_1_Base = fullfile(Path_Output_18, ...
    'Figure_1_Case1_Null_Distributions');

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [40, 70, 1650, 580], ...
    'Renderer', 'painters');

t = tiledlayout(fig, 1, 3, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

ax1 = nexttile(t);
draw_null_panel(ax1, ...
    Shape_10.TestStatistic, ...
    Shape_Summary_10.Observed_LR, ...
    Shape_Summary_10.P95_LR, ...
    'LR statistic', '$T_n^{LR}$', ...
    Color_All, Color_Tail, ...
    Color_Observed, Color_Critical);

ax2 = nexttile(t);
draw_null_panel(ax2, ...
    Shape_10.PIT_Pairwise_Delta, ...
    Shape_Summary_10.Observed_PIT_Pairwise_Delta, ...
    Shape_Summary_10.P95_PIT_Pairwise_Delta, ...
    'Pairwise PIT statistic: 10 bins', ...
    '$T_n^{\Delta}$', ...
    Color_All, Color_Tail, ...
    Color_Observed, Color_Critical);

ax3 = nexttile(t);
draw_null_panel(ax3, ...
    Shape_20.PIT_Pairwise_Delta, ...
    Shape_Summary_20.Observed_PIT_Pairwise_Delta, ...
    Shape_Summary_20.P95_PIT_Pairwise_Delta, ...
    'Pairwise PIT statistic: 20 bins', ...
    '$T_n^{\Delta}$', ...
    Color_All, Color_Tail, ...
    Color_Observed, Color_Critical);

save_figure(fig, Figure_1_Base, Resolution);
close(fig);


%% Figure 2: Case 2 simulated null distributions

Figure_2_Base = fullfile(Path_Output_18, ...
    'Figure_2_Case2_Null_Distributions');

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [40, 70, 1650, 580], ...
    'Renderer', 'painters');

t = tiledlayout(fig, 1, 3, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

ax1 = nexttile(t);
draw_null_panel(ax1, ...
    Distortion_10.TestStatistic, ...
    Distortion_Summary_10.Observed_LR, ...
    Distortion_Summary_10.P95_LR, ...
    'LR statistic', '$T_n^{LR}$', ...
    Color_All, Color_Tail, ...
    Color_Observed, Color_Critical);

ax2 = nexttile(t);
draw_null_panel(ax2, ...
    Distortion_10.PIT_Pairwise_Delta, ...
    Distortion_Summary_10.Observed_PIT_Pairwise_Delta, ...
    Distortion_Summary_10.P95_PIT_Pairwise_Delta, ...
    'Pairwise PIT statistic: 10 bins', ...
    '$T_n^{\Delta}$', ...
    Color_All, Color_Tail, ...
    Color_Observed, Color_Critical);

ax3 = nexttile(t);
draw_null_panel(ax3, ...
    Distortion_20.PIT_Pairwise_Delta, ...
    Distortion_Summary_20.Observed_PIT_Pairwise_Delta, ...
    Distortion_Summary_20.P95_PIT_Pairwise_Delta, ...
    'Pairwise PIT statistic: 20 bins', ...
    '$T_n^{\Delta}$', ...
    Color_All, Color_Tail, ...
    Color_Observed, Color_Critical);

save_figure(fig, Figure_2_Base, Resolution);
close(fig);


%% Figure 3: Beta selected by the alternative model in Case 2

Figure_3_Base = fullfile(Path_Output_18, ...
    'Figure_3_Selected_Beta_Distribution');

Beta_Grid = (0.88:0.01:1.02)';
Beta_Count = zeros(size(Beta_Grid));

for grid_idx = 1:numel(Beta_Grid)
    Beta_Count(grid_idx) = sum( ...
        abs(Distortion_10.Beta_B - Beta_Grid(grid_idx)) ...
        < 1e-10);
end

assert(sum(Beta_Count) == Num_Distortion, ...
    'Some estimated beta values are outside the stated beta grid.');

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [40, 70, 1500, 620], ...
    'Renderer', 'painters');

ax = axes(fig);
b = bar(ax, Beta_Grid, Beta_Count, 0.78, ...
    'FaceColor', Color_Beta, ...
    'EdgeColor', [0.25, 0.28, 0.30], ...
    'LineWidth', 0.7);

hold(ax, 'on');

hNull = xline(ax, 1.00, '--', ...
    '$\beta=1$ (null)', ...
    'Color', Color_Critical, ...
    'LineWidth', 1.6, ...
    'Interpreter', 'latex', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14, ...
    'LabelHorizontalAlignment', 'left', ...
    'LabelVerticalAlignment', 'middle');

hObserved = xline(ax, 0.92, '-', ...
    '$\widehat{\beta}_{\mathrm{obs}}=0.92$', ...
    'Color', Color_Observed, ...
    'LineWidth', 1.8, ...
    'Interpreter', 'latex', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14, ...
    'LabelHorizontalAlignment', 'left', ...
    'LabelVerticalAlignment', 'middle');

for grid_idx = 1:numel(Beta_Grid)
    if Beta_Count(grid_idx) > 0
        text(ax, Beta_Grid(grid_idx), ...
            Beta_Count(grid_idx) + 0.45, ...
            sprintf('%d', Beta_Count(grid_idx)), ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'bottom', ...
            'Interpreter', 'none', ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14);
    end
end

xlabel(ax, 'Selected $\widehat{\beta}$', ...
    'Interpreter', 'latex', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);
ylabel(ax, sprintf('Frequency (out of %d)', Num_Distortion), ...
    'Interpreter', 'none', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);
xticks(ax, Beta_Grid);
xticklabels(ax, compose('%.2f', Beta_Grid));
xtickangle(ax, 0);
xlim(ax, [Beta_Grid(1) - 0.008, Beta_Grid(end) + 0.008]);
ylim(ax, [0, max(Beta_Count) * 1.22]);
yticks(ax, 0:5:ceil(max(Beta_Count) * 1.2));
grid(ax, 'on');
ax.YGrid = 'on';
ax.XGrid = 'off';
box(ax, 'on');
set(ax, 'Layer', 'top');

legend(ax, [b, hNull, hObserved], ...
    {'Selected-beta frequency', ...
     'Undistorted null', ...
     'Observed-sample estimate'}, ...
    'Location', 'northwest', ...
    'Interpreter', 'none', ...
    'Box', 'off', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

save_figure(fig, Figure_3_Base, Resolution);
close(fig);


%% Completion message

fprintf('\nFigures 1-3 were created successfully.\n');
fprintf('Output folder:\n%s\n\n', Path_Output_18);
fprintf('Figure 1: %s\n', Figure_1_Base);
fprintf('Figure 2: %s\n', Figure_2_Base);
fprintf('Figure 3: %s\n', Figure_3_Base);


%% Local functions

function summary_row = get_summary_row(summary_table, num_bins)

    summary_row = summary_table( ...
        summary_table.Num_Bins == num_bins, :);

    assert(height(summary_row) == 1, ...
        'Expected exactly one summary row for %d bins.', ...
        num_bins);

end


function draw_null_panel(ax, values, observed_value, ...
    critical_value, panel_title, x_label, color_all, color_tail, ...
    color_observed, color_critical)

    values = values(isfinite(values));
    assert(~isempty(values), ...
        'No finite simulated statistics were supplied.');

    % With B = 50, ten bars are a reasonably fine upper limit:
    % approximately five simulated statistics per bar on average.
    num_bins = min(10, numel(values));
    x_min = min([values; observed_value; critical_value]);
    x_max = max([values; observed_value; critical_value]);
    x_span = x_max - x_min;

    if x_span <= eps(max(abs([x_min, x_max, 1])))
        x_span = max(abs(x_max), 1) * 0.1;
    end

    lower_limit = max(0, x_min - 0.06 * x_span);
    upper_limit = x_max + 0.08 * x_span;
    edges = linspace(lower_limit, upper_limit, num_bins + 1);

    h_all = histogram(ax, values, edges, ...
        'FaceColor', color_all, ...
        'EdgeColor', [0.30, 0.33, 0.36], ...
        'LineWidth', 0.7, ...
        'DisplayName', 'All simulations');

    hold(ax, 'on');

    tail_values = values(values >= observed_value);
    h_tail = histogram(ax, tail_values, edges, ...
        'FaceColor', color_tail, ...
        'EdgeColor', [0.45, 0.20, 0.16], ...
        'LineWidth', 0.7, ...
        'DisplayName', 'Simulations with T^(b) >= T_obs');

    xline(ax, observed_value, '-', ...
        sprintf('Observed = %.5g', observed_value), ...
        'Color', color_observed, ...
        'LineWidth', 1.8, ...
        'Interpreter', 'none', ...
        'FontName', 'Times New Roman', ...
        'FontSize', 14, ...
        'LabelHorizontalAlignment', 'left', ...
        'LabelVerticalAlignment', 'middle');

    xline(ax, critical_value, '--', ...
        sprintf('95%% critical = %.5g', critical_value), ...
        'Color', color_critical, ...
        'LineWidth', 1.6, ...
        'Interpreter', 'none', ...
        'FontName', 'Times New Roman', ...
        'FontSize', 14, ...
        'LabelHorizontalAlignment', 'right', ...
        'LabelVerticalAlignment', 'middle');

    title(ax, panel_title, ...
        'Interpreter', 'none', ...
        'FontWeight', 'normal', ...
        'FontName', 'Times New Roman', ...
        'FontSize', 14);
    xlabel(ax, x_label, ...
        'Interpreter', 'latex', ...
        'FontName', 'Times New Roman', ...
        'FontSize', 14);
    ylabel(ax, 'Frequency', ...
        'Interpreter', 'none', ...
        'FontName', 'Times New Roman', ...
        'FontSize', 14);

    xlim(ax, [lower_limit, upper_limit]);
    grid(ax, 'on');
    ax.XGrid = 'off';
    box(ax, 'on');
    set(ax, 'Layer', 'top');

    if strcmp(panel_title, 'LR statistic')
        legend(ax, [h_all, h_tail], ...
            {'All simulations', ...
             'Simulations with T^(b) >= T_obs'}, ...
            'Location', 'northeast', ...
            'Interpreter', 'none', ...
            'Box', 'off', ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14);
    end

end


function save_figure(fig, output_base, resolution)

    exportgraphics(fig, [output_base, '.png'], ...
        'Resolution', resolution, ...
        'BackgroundColor', 'white');

    exportgraphics(fig, [output_base, '.pdf'], ...
        'ContentType', 'vector', ...
        'BackgroundColor', 'white');

    savefig(fig, [output_base, '.fig']);

end
