clear; clc;

%% Paths

Path_MainFolder = 'D:\Google\我的雲端硬碟\學術｜研究與論文\論文著作\MLE Pricing Kernel';
Path_Output_18 = fullfile(Path_MainFolder, 'Code', '18  Output');

Path_Figures = fullfile(Path_Output_18, ...
    '05_Simulation_Diagnostics_and_Comparison_Plots');

if ~exist(Path_Figures, 'dir')
    mkdir(Path_Figures);
end


%% Load simulation results

Folder_1 = fullfile(Path_Output_18, ...
    '01_Shape_Null_ConstraintDGP');
Folder_2 = fullfile(Path_Output_18, ...
    '02_Shape_Alternative_UnconstraintDGP');
Folder_3 = fullfile(Path_Output_18, ...
    '03_Distortion_Null_UndistortedDGP');
Folder_4 = fullfile(Path_Output_18, ...
    '04_Distortion_Alternative_DistortedDGP');

Scalar_1 = readtable(fullfile(Folder_1, 'Simulation_Scalars.csv'));
Scalar_2 = readtable(fullfile(Folder_2, 'Simulation_Scalars.csv'));
Scalar_3 = readtable(fullfile(Folder_3, 'Simulation_Scalars.csv'));
Scalar_4 = readtable(fullfile(Folder_4, 'Simulation_Scalars.csv'));

Summary_1 = readtable(fullfile(Folder_1, 'Simulation_Summary.csv'));
Summary_2 = readtable(fullfile(Folder_2, 'Simulation_Summary.csv'));
Summary_3 = readtable(fullfile(Folder_3, 'Simulation_Summary.csv'));
Summary_4 = readtable(fullfile(Folder_4, 'Simulation_Summary.csv'));

Bins_1 = readtable(fullfile(Folder_1, 'Mean_PIT_Bins.csv'));
Bins_2 = readtable(fullfile(Folder_2, 'Mean_PIT_Bins.csv'));
Bins_3 = readtable(fullfile(Folder_3, 'Mean_PIT_Bins.csv'));
Bins_4 = readtable(fullfile(Folder_4, 'Mean_PIT_Bins.csv'));

Observed_PIT_File = load(fullfile( ...
    Path_Output_18, 'Observed_PIT_Statistics.mat'));
Observed_PIT = Observed_PIT_File.Observed_PIT;

Power_Summary = readtable(fullfile( ...
    Path_Output_18, 'Power_Summary.csv'));


%% Plot settings

set(groot, 'defaultAxesFontName', 'Times New Roman');
set(groot, 'defaultAxesFontSize', 11);
set(groot, 'defaultTextInterpreter', 'none');
set(groot, 'defaultLegendInterpreter', 'none');
set(groot, 'defaultAxesToolbarVisible', 'off');

Color_Blue = [0.20, 0.47, 0.67];
Color_Red  = [0.76, 0.25, 0.24];
Color_Gray = [0.55, 0.55, 0.55];
Color_Dark = [0.15, 0.20, 0.25];

Resolution = 300;
Num_Replications = height(Scalar_1);


%% Figure 01: Monotonicity null distribution

plot_null_distribution( ...
    Scalar_1.TestStatistic, ...
    Summary_1.Observed_TestStatistic(1), ...
    Summary_1.P95_TestStatistic(1), ...
    Color_Blue, ...
    'Monotonicity test under constrained DGP', ...
    '$2(LL_U-LL_C)$', ...
    fullfile(Path_Figures, ...
    '01_Monotonicity_Null_LR_Distribution.png'), ...
    Resolution, Num_Replications);


%% Figure 02: Monotonicity null versus alternative

plot_null_vs_alternative( ...
    Scalar_1.TestStatistic, ...
    Scalar_2.TestStatistic, ...
    Summary_1.Observed_TestStatistic(1), ...
    Summary_1.P95_TestStatistic(1), ...
    Color_Blue, Color_Red, ...
    'Monotonicity test: null versus U-shaped DGP', ...
    '$2(LL_U-LL_C)$', ...
    'Constrained DGP', 'U-shaped DGP', ...
    fullfile(Path_Figures, ...
    '02_Monotonicity_Null_vs_Alternative_LR.png'), ...
    Resolution, Num_Replications);


%% Figure 03: Distortion null distribution

plot_null_distribution( ...
    Scalar_3.TestStatistic, ...
    Summary_3.Observed_TestStatistic(1), ...
    Summary_3.P95_TestStatistic(1), ...
    Color_Blue, ...
    'Distortion test under undistorted DGP', ...
    '$2(LL_{\beta=0.92}-LL_{\beta=1})$', ...
    fullfile(Path_Figures, ...
    '03_Distortion_Null_LogLikelihood_Difference.png'), ...
    Resolution, Num_Replications);


%% Figure 04: Distortion null versus alternative

plot_null_vs_alternative( ...
    Scalar_3.TestStatistic, ...
    Scalar_4.TestStatistic, ...
    Summary_3.Observed_TestStatistic(1), ...
    Summary_3.P95_TestStatistic(1), ...
    Color_Blue, Color_Red, ...
    'Distortion test: null versus distorted DGP', ...
    '$2(LL_{\beta=0.92}-LL_{\beta=1})$', ...
    'Undistorted DGP', 'Distorted DGP', ...
    fullfile(Path_Figures, ...
    '04_Distortion_Null_vs_Alternative_LogLikelihood.png'), ...
    Resolution, Num_Replications);


%% Figure 05: Observed PIT, constraint versus unconstraint

plot_pit_comparison( ...
    Observed_PIT.Constraint.BinProbability, ...
    Observed_PIT.Unconstraint.BinProbability, ...
    'Constraint', 'Unconstraint', ...
    Color_Blue, Color_Red, ...
    'Observed PIT: constraint versus unconstraint', ...
    fullfile(Path_Figures, ...
    '05_Observed_PIT_Constraint_vs_Unconstraint.png'), ...
    Resolution);


%% Figure 06: Observed PIT, undistorted versus distorted

plot_pit_comparison( ...
    Observed_PIT.Undistorted.BinProbability, ...
    Observed_PIT.Distorted.BinProbability, ...
    'Undistorted', 'Distorted (beta = 0.92)', ...
    Color_Blue, Color_Red, ...
    'Observed PIT: undistorted versus distorted', ...
    fullfile(Path_Figures, ...
    '06_Observed_PIT_Undistorted_vs_Distorted.png'), ...
    Resolution);


%% Figure 07: Mean simulated PIT for monotonicity experiments

fig = figure('Position', [80, 80, 1100, 430], 'Color', 'w');
tiledlayout(1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

nexttile;
draw_mean_pit_bins(Bins_1, ...
    'Constraint', 'Unconstraint', ...
    Color_Blue, Color_Red, ...
    'Constrained DGP');

nexttile;
draw_mean_pit_bins(Bins_2, ...
    'Constraint', 'Unconstraint', ...
    Color_Blue, Color_Red, ...
    'U-shaped DGP');

sgtitle(sprintf( ...
    'Mean simulated PIT: monotonicity experiments (N_{sim} = %d)', ...
    Num_Replications), 'Interpreter', 'tex');

hide_axes_toolbars(fig);
exportgraphics(fig, fullfile(Path_Figures, ...
    '07_Simulated_Mean_PIT_Monotonicity.png'), ...
    'Resolution', Resolution);
close(fig);


%% Figure 08: Mean simulated PIT for distortion experiments

fig = figure('Position', [80, 80, 1100, 430], 'Color', 'w');
tiledlayout(1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

nexttile;
draw_mean_pit_bins(Bins_3, ...
    'Undistorted', 'Distorted', ...
    Color_Blue, Color_Red, ...
    'Undistorted DGP');

nexttile;
draw_mean_pit_bins(Bins_4, ...
    'Undistorted', 'Distorted', ...
    Color_Blue, Color_Red, ...
    'Distorted DGP');

sgtitle(sprintf( ...
    'Mean simulated PIT: distortion experiments (N_{sim} = %d)', ...
    Num_Replications), 'Interpreter', 'tex');

hide_axes_toolbars(fig);
exportgraphics(fig, fullfile(Path_Figures, ...
    '08_Simulated_Mean_PIT_Distortion.png'), ...
    'Resolution', Resolution);
close(fig);


%% Figure 09: PIT sup-norm distributions across all experiments

Values = [ ...
    Scalar_1.PIT_Sup_A; Scalar_1.PIT_Sup_B; ...
    Scalar_2.PIT_Sup_A; Scalar_2.PIT_Sup_B; ...
    Scalar_3.PIT_Sup_A; Scalar_3.PIT_Sup_B; ...
    Scalar_4.PIT_Sup_A; Scalar_4.PIT_Sup_B];

Labels = [ ...
    repmat("Shape null: C", height(Scalar_1), 1); ...
    repmat("Shape null: U", height(Scalar_1), 1); ...
    repmat("Shape alt: C", height(Scalar_2), 1); ...
    repmat("Shape alt: U", height(Scalar_2), 1); ...
    repmat("Dist. null: N", height(Scalar_3), 1); ...
    repmat("Dist. null: D", height(Scalar_3), 1); ...
    repmat("Dist. alt: N", height(Scalar_4), 1); ...
    repmat("Dist. alt: D", height(Scalar_4), 1)];

Label_Order = [ ...
    "Shape null: C", "Shape null: U", ...
    "Shape alt: C", "Shape alt: U", ...
    "Dist. null: N", "Dist. null: D", ...
    "Dist. alt: N", "Dist. alt: D"];

Labels = categorical(Labels, Label_Order, 'Ordinal', true);

fig = figure('Position', [80, 80, 1200, 500], 'Color', 'w');
boxchart(Labels, Values, ...
    'BoxFaceColor', Color_Gray, ...
    'MarkerColor', Color_Dark);
grid on;
ylabel('PIT sup norm');
title(sprintf( ...
    'PIT distance from Uniform(0,1) across experiments (N_{sim} = %d)', ...
    Num_Replications), 'Interpreter', 'tex');
xtickangle(25);

hide_axes_toolbars(fig);
exportgraphics(fig, fullfile(Path_Figures, ...
    '09_PIT_SupNorm_All_Experiments.png'), ...
    'Resolution', Resolution);
close(fig);


%% Figure 10: Pilot power summary

fig = figure('Position', [80, 80, 700, 480], 'Color', 'w');

Power_Labels = categorical( ...
    ["Monotonicity"; "Fixed beta: 0.92 vs 1.00"]);
Power_Labels = reordercats(Power_Labels, ...
    ["Monotonicity", "Fixed beta: 0.92 vs 1.00"]);

bar(Power_Labels, Power_Summary.EstimatedPower_5pct, ...
    'FaceColor', Color_Blue, 'EdgeColor', 'none');

ylim([0, 1]);
yline(0.8, '--', '80% reference', ...
    'Color', Color_Gray, 'LineWidth', 1.2);
ylabel('Estimated power');
title(sprintf('Pilot power estimates (N_{sim} = %d)', Num_Replications), ...
    'Interpreter', 'tex');
grid on;
set(gca, 'TickLabelInterpreter', 'none');

for i = 1:height(Power_Summary)
    text(i, Power_Summary.EstimatedPower_5pct(i) + 0.035, ...
        sprintf('%.0f%%', ...
        100 * Power_Summary.EstimatedPower_5pct(i)), ...
        'HorizontalAlignment', 'center', ...
        'Interpreter', 'none');
end

hide_axes_toolbars(fig);
exportgraphics(fig, fullfile(Path_Figures, ...
    '10_Pilot_Power_Summary.png'), ...
    'Resolution', Resolution);
close(fig);


%% Figure 11: Professor's Delta under the monotonicity null

% Delta compares the two models' PIT histograms bin by bin:
% Delta = max_j |p_A,j - p_B,j|, j = 1,...,10.
Observed_Delta_Shape = max(abs( ...
    Observed_PIT.Constraint.BinProbability(:) - ...
    Observed_PIT.Unconstraint.BinProbability(:)));

plot_pit_delta_null_distribution( ...
    Scalar_1.PIT_Pairwise_Delta, ...
    Observed_Delta_Shape, ...
    Color_Blue, ...
    'PIT-bin Delta under constrained DGP', ...
    'Constraint versus unconstraint', ...
    fullfile(Path_Figures, ...
    '11_Monotonicity_PIT_Delta_Null_Distribution.png'), ...
    Resolution, Num_Replications);


%% Figure 12: Professor's Delta under the distortion null

Observed_Delta_Distortion = max(abs( ...
    Observed_PIT.Undistorted.BinProbability(:) - ...
    Observed_PIT.Distorted.BinProbability(:)));

plot_pit_delta_null_distribution( ...
    Scalar_3.PIT_Pairwise_Delta, ...
    Observed_Delta_Distortion, ...
    Color_Blue, ...
    'PIT-bin Delta under undistorted DGP', ...
    'Undistorted versus distorted', ...
    fullfile(Path_Figures, ...
    '12_Distortion_PIT_Delta_Null_Distribution.png'), ...
    Resolution, Num_Replications);


fprintf('\nAll simulation figures were saved to:\n%s\n', Path_Figures);


%% Local plotting functions

function plot_null_distribution( ...
    statistics, observed_statistic, critical_value, ...
    face_color, plot_title, x_label, output_file, ...
    resolution, num_replications)

    statistics = statistics(isfinite(statistics));

    fig = figure('Position', [80, 80, 720, 500], 'Color', 'w');

    histogram(statistics, ...
        'NumBins', min(8, max(4, round(sqrt(numel(statistics))))), ...
        'Normalization', 'probability', ...
        'FaceColor', face_color, ...
        'FaceAlpha', 0.75, ...
        'EdgeColor', 'w');
    hold on;

    xline(observed_statistic, '-', ...
        sprintf('Observed = %.3f', observed_statistic), ...
        'Color', [0.76, 0.25, 0.24], ...
        'LineWidth', 2, ...
        'LabelOrientation', 'horizontal');

    xline(critical_value, '--', ...
        sprintf('95%% critical = %.3f', critical_value), ...
        'Color', [0.15, 0.20, 0.25], ...
        'LineWidth', 2, ...
        'LabelOrientation', 'horizontal');

    hold off;
    grid on;
    xlabel(x_label, 'Interpreter', 'latex');
    ylabel('Fraction of simulations');
    title(sprintf('%s (N_{sim} = %d)', plot_title, num_replications), ...
        'Interpreter', 'tex');

    hide_axes_toolbars(fig);
    exportgraphics(fig, output_file, 'Resolution', resolution);
    close(fig);
end


function plot_null_vs_alternative( ...
    null_statistics, alternative_statistics, ...
    observed_statistic, critical_value, ...
    null_color, alternative_color, ...
    plot_title, x_label, null_name, alternative_name, ...
    output_file, resolution, num_replications)

    null_statistics = null_statistics(isfinite(null_statistics));
    alternative_statistics = ...
        alternative_statistics(isfinite(alternative_statistics));

    all_statistics = [null_statistics; alternative_statistics];
    min_stat = min(all_statistics);
    max_stat = max(all_statistics);

    if min_stat == max_stat
        min_stat = min_stat - 0.5;
        max_stat = max_stat + 0.5;
    end

    num_bins = min(8, max(4, round(sqrt(numel(null_statistics)))));
    edges = linspace(min_stat, max_stat, num_bins + 1);

    fig = figure('Position', [80, 80, 760, 520], 'Color', 'w');

    histogram(null_statistics, edges, ...
        'Normalization', 'probability', ...
        'FaceColor', null_color, ...
        'FaceAlpha', 0.55, ...
        'EdgeColor', 'w', ...
        'DisplayName', null_name);
    hold on;

    histogram(alternative_statistics, edges, ...
        'Normalization', 'probability', ...
        'FaceColor', alternative_color, ...
        'FaceAlpha', 0.45, ...
        'EdgeColor', 'w', ...
        'DisplayName', alternative_name);

    xline(observed_statistic, '-', ...
        sprintf('Observed = %.3f', observed_statistic), ...
        'Color', [0.55, 0.10, 0.10], ...
        'LineWidth', 2, ...
        'HandleVisibility', 'off');

    xline(critical_value, '--', ...
        sprintf('95%% critical = %.3f', critical_value), ...
        'Color', [0.15, 0.20, 0.25], ...
        'LineWidth', 2, ...
        'HandleVisibility', 'off');

    hold off;
    grid on;
    xlabel(x_label, 'Interpreter', 'latex');
    ylabel('Fraction of simulations');
    title(sprintf('%s (N_{sim} = %d)', plot_title, num_replications), ...
        'Interpreter', 'tex');
    legend('Location', 'best', 'Box', 'off', ...
        'Interpreter', 'none');

    hide_axes_toolbars(fig);
    exportgraphics(fig, output_file, 'Resolution', resolution);
    close(fig);
end


function plot_pit_comparison( ...
    probability_A, probability_B, ...
    name_A, name_B, color_A, color_B, ...
    plot_title, output_file, resolution)

    probabilities = [probability_A(:), probability_B(:)];

    fig = figure('Position', [80, 80, 800, 500], 'Color', 'w');
    bars = bar(1:10, probabilities, 'grouped');
    bars(1).FaceColor = color_A;
    bars(2).FaceColor = color_B;
    bars(1).EdgeColor = 'none';
    bars(2).EdgeColor = 'none';
    hold on;
    yline(0.1, 'k--', 'Uniform target = 0.10', ...
        'LineWidth', 1.5, ...
        'LabelHorizontalAlignment', 'left');
    hold off;

    grid on;
    xlabel('PIT bin');
    ylabel('Probability');
    title(plot_title, 'Interpreter', 'none');
    legend({name_A, name_B}, ...
        'Location', 'best', 'Box', 'off', ...
        'Interpreter', 'none');
    xlim([0.4, 10.6]);

    upper_limit = max([0.13; probabilities(:) * 1.15]);
    ylim([0, upper_limit]);

    hide_axes_toolbars(fig);
    exportgraphics(fig, output_file, 'Resolution', resolution);
    close(fig);
end


function draw_mean_pit_bins( ...
    bin_table, name_A, name_B, color_A, color_B, plot_title)

    probabilities = [ ...
        bin_table.MeanProbability_A, ...
        bin_table.MeanProbability_B];

    bars = bar(bin_table.Bin, probabilities, 'grouped');
    bars(1).FaceColor = color_A;
    bars(2).FaceColor = color_B;
    bars(1).EdgeColor = 'none';
    bars(2).EdgeColor = 'none';

    hold on;
    yline(0.1, 'k--', 'Uniform target', ...
        'LineWidth', 1.3, ...
        'LabelHorizontalAlignment', 'left');
    hold off;

    grid on;
    xlabel('PIT bin');
    ylabel('Mean probability');
    title(plot_title, 'Interpreter', 'none');
    legend({name_A, name_B}, ...
        'Location', 'best', 'Box', 'off', ...
        'Interpreter', 'none');
    xlim([0.4, 10.6]);

    upper_limit = max([0.13; probabilities(:) * 1.15]);
    ylim([0, upper_limit]);
end


function plot_pit_delta_null_distribution( ...
    null_delta, observed_delta, face_color, ...
    plot_title, comparison_label, output_file, ...
    resolution, num_replications)

    null_delta = null_delta(isfinite(null_delta));

    if isempty(null_delta)
        error('No finite PIT pairwise Delta values are available.');
    end

    critical_value = prctile(null_delta, 95);
    p_value = (1 + sum(null_delta >= observed_delta)) / ...
        (1 + numel(null_delta));

    % A simple Gaussian kernel density curve is drawn over the histogram.
    % This avoids assuming that Delta follows a normal distribution.
    n = numel(null_delta);
    sample_std = std(null_delta);
    sample_iqr = prctile(null_delta, 75) - ...
        prctile(null_delta, 25);
    robust_scale = min(sample_std, sample_iqr / 1.34);

    if ~isfinite(robust_scale) || robust_scale <= 0
        robust_scale = max( ...
            (max(null_delta) - min(null_delta)) / 4, 1e-4);
    end

    bandwidth = 0.9 * robust_scale * n^(-1/5);

    if ~isfinite(bandwidth) || bandwidth <= 0
        bandwidth = 1e-4;
    end

    x_left = max(0, min([null_delta; observed_delta]) - 2 * bandwidth);
    x_right = max([null_delta; observed_delta; critical_value]) + ...
        2 * bandwidth;

    if x_right <= x_left
        x_right = x_left + 5 * bandwidth;
    end

    x_grid = linspace(x_left, x_right, 300);
    z = (x_grid(:) - null_delta(:)') ./ bandwidth;
    density = mean(exp(-0.5 .* z.^2), 2) ./ ...
        (sqrt(2 * pi) * bandwidth);

    fig = figure('Position', [80, 80, 780, 520], 'Color', 'w');

    histogram(null_delta, ...
        'NumBins', min(8, max(4, round(sqrt(n)))), ...
        'Normalization', 'pdf', ...
        'FaceColor', face_color, ...
        'FaceAlpha', 0.35, ...
        'EdgeColor', 'w', ...
        'DisplayName', 'Simulated Delta');
    hold on;

    plot(x_grid, density, ...
        'Color', face_color, ...
        'LineWidth', 2.5, ...
        'DisplayName', 'Smoothed null density');

    xline(observed_delta, '-', ...
        sprintf('Observed Delta = %.4f', observed_delta), ...
        'Color', [0.76, 0.25, 0.24], ...
        'LineWidth', 2, ...
        'LabelOrientation', 'horizontal', ...
        'HandleVisibility', 'off');

    xline(critical_value, '--', ...
        sprintf('95%% critical = %.4f', critical_value), ...
        'Color', [0.15, 0.20, 0.25], ...
        'LineWidth', 2, ...
        'LabelOrientation', 'horizontal', ...
        'HandleVisibility', 'off');

    hold off;
    grid on;
    xlabel('$\Delta=\max_j|\hat p_{A,j}-\hat p_{B,j}|$', ...
        'Interpreter', 'latex');
    ylabel('Estimated density under H_0', 'Interpreter', 'tex');
    title({sprintf('%s (N_{sim} = %d)', plot_title, num_replications), ...
        sprintf('%s; bootstrap p-value = %.3f', ...
        comparison_label, p_value)}, ...
        'Interpreter', 'tex');
    legend('Location', 'southeast', 'Box', 'off', ...
        'Interpreter', 'none');

    hide_axes_toolbars(fig);
    exportgraphics(fig, output_file, 'Resolution', resolution);
    close(fig);

    fprintf(['%s: observed Delta = %.6f, 95%% critical = %.6f, ', ...
        'bootstrap p-value = %.6f\n'], ...
        comparison_label, observed_delta, critical_value, p_value);
end


function hide_axes_toolbars(fig)

    axes_handles = findall(fig, 'Type', 'axes');

    for i = 1:numel(axes_handles)
        axtoolbar(axes_handles(i), {});
    end
end
